Update email.yaml

diff --git a/.github/workflows/email.yaml b/.github/workflows/email.yaml
--- a/.github/workflows/email.yaml
+++ b/.github/workflows/email.yaml
@@ -10,58 +10,63 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PAT }}
-
-      - name: Build Docker Image
+      - name: Checkout Repository
         run: |
-          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest .
+            docker --version
+            python3 --version
 
-      - name: Push Docker Image to Docker Hub
-        run: |
-          docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
+  #     - name: Login to Docker Hub
+  #       uses: docker/login-action@v2
+  #       with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_PAT }}
+
+  #     - name: Build Docker Image
+  #       run: |
+  #         docker build -t ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest .
+
+  #     - name: Push Docker Image to Docker Hub
+  #       run: |
+  #         docker push ${{ secrets.DOCKER_USERNAME }}/my-flask-app:latest
 
 
-      - name: Run Container
-        run: |
-          docker run -d --name flask-container -p 5000:5000 my-flask-app
+  #     - name: Run Container
+  #       run: |
+  #         docker run -d --name flask-container -p 5000:5000 my-flask-app
 
-      - name: Wait for Container to Start
-        run: sleep 10
+  #     - name: Wait for Container to Start
+  #       run: sleep 10
 
-      - name: Extract Message from Flask App
-        run: |
-           MESSAGE=$(curl -s http://localhost:5000)
-           echo "FLASK_MESSAGE=$MESSAGE" >> $GITHUB_ENV
+  #     - name: Extract Message from Flask App
+  #       run: |
+  #          MESSAGE=$(curl -s http://localhost:5000)
+  #          echo "FLASK_MESSAGE=$MESSAGE" >> $GITHUB_ENV
 
-      - name: Check if Container is Running
-        run: |
-          if docker ps | grep -q flask-container; then
-            echo "CONTAINER_STATUS=running" >> $GITHUB_ENV
-          else
-            echo "CONTAINER_STATUS=failed" >> $GITHUB_ENV
-            exit 1
-          fi
+  #     - name: Check if Container is Running
+  #       run: |
+  #         if docker ps | grep -q flask-container; then
+  #           echo "CONTAINER_STATUS=running" >> $GITHUB_ENV
+  #         else
+  #           echo "CONTAINER_STATUS=failed" >> $GITHUB_ENV
+  #           exit 1
+  #         fi
 
-  send_email:
-    needs: build_and_run_container
-    runs-on: ubuntu-latest
-    if: success()  # Only runs if the container is running
-    steps:
-      - name: Send Email Notification
-        uses: dawidd6/action-send-mail@v3
-        with:
-          server_address: smtp.gmail.com
-          server_port: 587
-          username: ${{ secrets.EMAIL_USERNAME }}
-          password: ${{ secrets.EMAIL_PASSWORD }}
-          subject: "Flask App Deployment Successful ✅"
-          body: "${{ env.FLASK_MESSAGE }}"  # Use the same message from Flask
-          to: "raihaniqbal@kpmg.com" # Replace with recipient email
-          from: "GitHub Actions rockrocking1995@gmail.com"
-          content_type: text/plain
+  # send_email:
+  #   needs: build_and_run_container
+  #   runs-on: ubuntu-latest
+  #   if: success()  # Only runs if the container is running
+  #   steps:
+  #     - name: Send Email Notification
+  #       uses: dawidd6/action-send-mail@v3
+  #       with:
+  #         server_address: smtp.gmail.com
+  #         server_port: 587
+  #         username: ${{ secrets.EMAIL_USERNAME }}
+  #         password: ${{ secrets.EMAIL_PASSWORD }}
+  #         subject: "Flask App Deployment Successful ✅"
+  #         body: "${{ env.FLASK_MESSAGE }}"  # Use the same message from Flask
+  #         to: "raihaniqbal@kpmg.com" # Replace with recipient email
+  #         from: "GitHub Actions rockrocking1995@gmail.com"
+  #         content_type: text/plain
 
 
